# Generated by Django 5.1.7 on 2025-05-27 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplies',
            name='user',
        ),
        migrations.CreateModel(
            name='Lendingsupplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend', models.IntegerField()),
                ('date', models.DateField()),
                ('destruction', models.IntegerField()),
                ('lendid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.supplies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
