# Generated by Django 5.1.7 on 2025-05-27 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_remove_supplies_user_lendingsupplies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplies',
            name='allsupplies',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplies',
            name='borrowed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplies',
            name='lend',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplies',
            name='stamp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplies',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplies',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
