# Generated by Django 5.1.7 on 2025-05-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_supplies_allsupplies_supplies_borrowed_supplies_lend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingsupplies',
            name='destruction',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='borrowed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='lend',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='stamp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
