# Generated by Django 5.1.7 on 2025-05-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_alter_lendingsupplies_destruction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingsupplies',
            name='destruction',
            field=models.IntegerField(choices=[], default=0),
        ),
    ]
