# Generated by Django 5.1.7 on 2025-05-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0007_alter_lendingsupplies_destruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingsupplies',
            name='destruction',
            field=models.IntegerField(choices=[], default=0, max_length=100),
        ),
    ]
